# Arabic translations for Openpilot-v0.7.1-release package.
# Copyright (C) 2020 THE Openpilot-v0.7.1-release'S COPYRIGHT HOLDER
# This file is distributed under the same license as the Openpilot-v0.7.1-release package.
# xx979xx <xx979xx@gmail.com>, 2020.
#
msgid ""
msgstr ""
"Project-Id-Version: Openpilot-v0.7.1-release\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2020-02-03 17:07+0300\n"
"PO-Revision-Date: 2020-02-03 17:20+0300\n"
"Last-Translator: xx979xx <xx979xx@gmail.com>\n"
"Language-Team: Arabic\n"
"Language: ar_EG\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: selfdrive/controls/lib/alerts.py:163
msgid "Accuracy Is High"
msgstr "دقة عالية"
#: selfdrive/controls/lib/alerts.py:156
msgid "Accuracy Is Low"
msgstr "دقة منخفضة"
#: selfdrive/controls/lib/alerts.py:177 selfdrive/controls/lib/alerts.py:184
#: selfdrive/controls/lib/alerts.py:191
msgid "Always keep hands on wheel and eyes on road"
msgstr "احرص دائمًا على القيادة والعينين على الطريق"
#: selfdrive/controls/lib/alerts.py:729
msgid "An Update Check Is Required to Engage"
msgstr "التحقق من التحديث مطلوب للمشاركة"
#: selfdrive/controls/lib/alerts.py:78 selfdrive/controls/lib/alerts.py:85
msgid "BRAKE!"
msgstr "الفرامل!"
#: selfdrive/controls/lib/alerts.py:176
msgid "Be ready to take over at any time"
msgstr "كن مستعدًا لتولي المسؤولية في أي وقت"
#: selfdrive/controls/lib/alerts.py:303
msgid "Brake Hold Active"
msgstr "الفرامل عقد بالموقع"
#: selfdrive/controls/lib/alerts.py:460 selfdrive/controls/lib/alerts.py:609
msgid "CAN Error: Check Connections"
msgstr "خطأ CAN: التحقق من الاتصالات"
#: selfdrive/controls/lib/alerts.py:367 selfdrive/controls/lib/alerts.py:539
msgid "Calibration Invalid: Reposition EON and Recalibrate"
msgstr "المعايرة غير صالحة: إعادة وضع EON وإعادة المعايرة"
#: selfdrive/controls/lib/alerts.py:374 selfdrive/controls/lib/alerts.py:546
msgid "Calibration in Progress"
msgstr "المعايرة في التقدم"
#: selfdrive/controls/lib/alerts.py:714
msgid "Calibration in Progress: "
msgstr "المعايرة في التقدم:"
#: selfdrive/controls/lib/alerts.py:764
msgid "Car Unrecognized"
msgstr "سيارة غير معترف بها"
#: selfdrive/controls/lib/alerts.py:252
msgid "Changing Lane"
msgstr "تغيير لين"
#: selfdrive/controls/lib/alerts.py:409 selfdrive/controls/lib/alerts.py:665
msgid "Communication Issue between Processes"
msgstr "مشكلة التواصل بين العمليات"
#: selfdrive/controls/lib/alerts.py:735
msgid "Community Feature Detected"
msgstr "تم اكتشاف ميزة المجتمع"
#: selfdrive/controls/lib/alerts.py:446 selfdrive/controls/lib/alerts.py:602
msgid "Controls Failed"
msgstr "فشل الضوابط"
#: selfdrive/controls/lib/alerts.py:453
msgid "Controls Mismatch"
msgstr "ضوابط عدم تطابق"
#: selfdrive/controls/lib/alerts.py:317 selfdrive/controls/lib/alerts.py:474
#: selfdrive/controls/lib/alerts.py:623
msgid "Cruise Fault: Restart the Car"
msgstr "خطأ كروز: إعادة تشغيل السيارة"
#: selfdrive/controls/lib/alerts.py:700 selfdrive/controls/lib/alerts.py:707
msgid "Cruise Fault: Restart the car to engage"
msgstr "خطأ كروز: إعادة تشغيل السيارة للانخراط"
#: selfdrive/controls/lib/alerts.py:495
msgid "Cruise Is Off"
msgstr "كروز هو خارج"
#: selfdrive/controls/lib/alerts.py:644
msgid "Cruise is Off"
msgstr "كروز هو خارج"
#: selfdrive/controls/lib/alerts.py:232
msgid "DEBUG ALERT"
msgstr "ديب ألت"
#: selfdrive/controls/lib/alerts.py:127 selfdrive/controls/lib/alerts.py:148
msgid "DISENGAGE IMMEDIATELY"
msgstr "فك الارتباط على الفور"
#: selfdrive/controls/lib/alerts.py:169
msgid "DISENGAGEMENT REQUIRED"
msgstr "الانفصال المطلوب"
#: selfdrive/controls/lib/alerts.py:162
msgid "DRIVER MONITOR IS AVAILABLE"
msgstr "رصد سائق متاح"
#: selfdrive/controls/lib/alerts.py:155
msgid "DRIVER MONITOR IS UNAVAILABLE"
msgstr "مراقبة السائق غير متوفر"
#: selfdrive/controls/lib/alerts.py:763
msgid "Dashcam Mode"
msgstr "وضع Dashcam"
#: selfdrive/controls/lib/alerts.py:183
msgid "Dashcam mode"
msgstr "وضع Dashcam"
#: selfdrive/controls/lib/alerts.py:190
msgid "Dashcam mode with unsupported car"
msgstr "وضع Dashcam مع سيارة غير مدعومة"
#: selfdrive/controls/lib/alerts.py:275
msgid "Data Needed for Calibration. Upload Drive, Try Again"
msgstr "البيانات اللازمة للمعايرة. تحميل حملة ، حاول مرة أخرى"
#: selfdrive/controls/lib/alerts.py:345
msgid "Distraction Level Too High"
msgstr "مستوى الهاء عالية جدا"
#: selfdrive/controls/lib/alerts.py:381
msgid "Door Open"
msgstr "الباب مفتوح"
#: selfdrive/controls/lib/alerts.py:553
msgid "Door open"
msgstr "الباب مفتوح"
#: selfdrive/controls/lib/alerts.py:715
msgid "Drive Above "
msgstr "حملة أعلاه"
#: selfdrive/controls/lib/alerts.py:395 selfdrive/controls/lib/alerts.py:567
msgid "ESP Off"
msgstr "ESP معطلة"
#: selfdrive/controls/lib/alerts.py:736
msgid "Enable Community Features in Developer Settings"
msgstr "تمكين ميزات المجتمع في إعدادات المطور"
#: selfdrive/controls/lib/alerts.py:198
msgid "Ethical Dilemma Detected"
msgstr "الكشف عن المعضلة الأخلاقية"
#: selfdrive/controls/lib/alerts.py:630
msgid "Gas Error: Restart the Car"
msgstr "خطأ الغاز: إعادة تشغيل السيارة"
#: selfdrive/controls/lib/alerts.py:481
msgid "Gas Fault: Restart the Car"
msgstr "خطأ الغاز: إعادة تشغيل السيارة"
#: selfdrive/controls/lib/alerts.py:360 selfdrive/controls/lib/alerts.py:532
msgid "Gear not D"
msgstr "جير لا د"
#: selfdrive/controls/lib/alerts.py:120
msgid "KEEP EYES ON ROAD"
msgstr "تبقي عيون على الطريق"
#: selfdrive/controls/lib/alerts.py:113
msgid "KEEP EYES ON ROAD: User Appears Distracted"
msgstr "إبقاء العينين على الطريق: يبدو المستخدم مشتتا"
#: selfdrive/controls/lib/alerts.py:467 selfdrive/controls/lib/alerts.py:616
msgid "LKAS Fault: Restart the Car"
msgstr "خطأ LKAS: إعادة تشغيل السيارة"
#: selfdrive/controls/lib/alerts.py:693
msgid "LKAS Fault: Restart the car to engage"
msgstr "خطأ LKAS: أعد تشغيل السيارة للانخراط"
#: selfdrive/controls/lib/alerts.py:779
msgid "Lane Departure Detected"
msgstr "حارة رحيل الكشف"
#: selfdrive/controls/lib/alerts.py:324 selfdrive/controls/lib/alerts.py:402
msgid "Low Battery"
msgstr "البطارية ضعيفة"
#: selfdrive/controls/lib/alerts.py:438 selfdrive/controls/lib/alerts.py:686
msgid "Low Memory: Reboot Your EON"
msgstr "ذاكرة منخفضة: إعادة تشغيل EON الخاص بك"
#: selfdrive/controls/lib/alerts.py:268
msgid "Main Switch Off"
msgstr "مفتاح الاغلاق"
#: selfdrive/controls/lib/alerts.py:239 selfdrive/controls/lib/alerts.py:246
#: selfdrive/controls/lib/alerts.py:253
msgid "Monitor Other Vehicles"
msgstr "مراقبة المركبات الأخرى"
#: selfdrive/controls/lib/alerts.py:651
msgid "No Close Lead Car"
msgstr "لا أغلق سيارة الرصاص"
#: selfdrive/controls/lib/alerts.py:331 selfdrive/controls/lib/alerts.py:742
msgid "No Data from EON Sensors"
msgstr "لا توجد بيانات من EON Sensors"
#: selfdrive/controls/lib/alerts.py:510
msgid "No close lead car"
msgstr "لا سيارة الرصاص وثيق"
#: selfdrive/controls/lib/alerts.py:170 selfdrive/controls/lib/alerts.py:574
msgid "Not in Geofenced Area"
msgstr "ليس في المنطقة الجغرافية"
#: selfdrive/controls/lib/alerts.py:282
msgid "Out of Storage Space"
msgstr "نفاد مساحة التخزين"
#: selfdrive/controls/lib/alerts.py:310
msgid "Park Brake Engaged"
msgstr "بارك الفرامل مخطوبة"
#: selfdrive/controls/lib/alerts.py:289
msgid "Pedal Pressed During Attempt"
msgstr "ضغط الدواسة أثناء المحاولة"
#: selfdrive/controls/lib/alerts.py:502 selfdrive/controls/lib/alerts.py:658
msgid "Planner Solution Error"
msgstr "خطأ في مخطط الحل"
#: selfdrive/controls/lib/alerts.py:679
msgid "Please Connect to Internet"
msgstr "يرجى الاتصال بالإنترنت"
#: selfdrive/controls/lib/alerts.py:728
msgid "Please connect to Internet"
msgstr "يرجى الاتصال بالإنترنت"
#: selfdrive/controls/lib/alerts.py:219
msgid "Press Resume to Move"
msgstr "اضغط على استئناف للتحرك"
#: selfdrive/controls/lib/alerts.py:756
msgid "RAM Critically Low"
msgstr "ذاكرة الوصول العشوائي منخفضة للغاية"
#: selfdrive/controls/lib/alerts.py:416 selfdrive/controls/lib/alerts.py:672
msgid "Radar Communication Issue"
msgstr "رادار الاتصالات العدد"
#: selfdrive/controls/lib/alerts.py:423 selfdrive/controls/lib/alerts.py:430
#: selfdrive/controls/lib/alerts.py:581 selfdrive/controls/lib/alerts.py:588
msgid "Radar Error: Restart the Car"
msgstr "خطأ الرادار: إعادة تشغيل السيارة"
#: selfdrive/controls/lib/alerts.py:743 selfdrive/controls/lib/alerts.py:750
#: selfdrive/controls/lib/alerts.py:757
msgid "Reboot your EON"
msgstr "إعادة تشغيل EON الخاص بك"
#: selfdrive/controls/lib/alerts.py:212
msgid "Resume Driving Manually"
msgstr "استئناف القيادة يدويا"
#: selfdrive/controls/lib/alerts.py:488 selfdrive/controls/lib/alerts.py:637
msgid "Reverse Gear"
msgstr "عكس العتاد"
#: selfdrive/controls/lib/alerts.py:79 selfdrive/controls/lib/alerts.py:86
msgid "Risk of Collision"
msgstr "خطر الاصطدام"
#: selfdrive/controls/lib/alerts.py:218
msgid "STOPPED"
msgstr "توقفت"
#: selfdrive/controls/lib/alerts.py:388
msgid "Seatbelt Unlatched"
msgstr "حزام الأمان غير مسبوق"
#: selfdrive/controls/lib/alerts.py:560
msgid "Seatbelt unlatched"
msgstr "حزام الأمان غير مفتوح"
#: selfdrive/controls/lib/alerts.py:338 selfdrive/controls/lib/alerts.py:749
msgid "Speaker not found"
msgstr "المتكلم غير موجود"
#: selfdrive/controls/lib/alerts.py:296
msgid "Speed Too Low"
msgstr "سرعة منخفضة جدا"
#: selfdrive/controls/lib/alerts.py:517
msgid "Speed too low"
msgstr "سرعة منخفضة جدا"
#: selfdrive/controls/lib/alerts.py:238
msgid "Steer Left to Start Lane Change"
msgstr "توجيه اليسار لبدء تغيير حارة"
#: selfdrive/controls/lib/alerts.py:245
msgid "Steer Right to Start Lane Change"
msgstr "توجيه الحق في بدء تغيير حارة"
#: selfdrive/controls/lib/alerts.py:226
msgid "Steer Unavailable Below "
msgstr "توجيه غير متاح أدناه"
#: selfdrive/controls/lib/alerts.py:100 selfdrive/controls/lib/alerts.py:107
#: selfdrive/controls/lib/alerts.py:205
msgid "Steering Temporarily Unavailable"
msgstr "التوجيه غير متاح مؤقتًا"
#: selfdrive/controls/lib/alerts.py:353
msgid "System Overheated"
msgstr "نظام محموم"
#: selfdrive/controls/lib/alerts.py:525
msgid "System overheated"
msgstr "نظام محموما"
#: selfdrive/controls/lib/alerts.py:92 selfdrive/controls/lib/alerts.py:99
#: selfdrive/controls/lib/alerts.py:106 selfdrive/controls/lib/alerts.py:211
#: selfdrive/controls/lib/alerts.py:225 selfdrive/controls/lib/alerts.py:259
#: selfdrive/controls/lib/alerts.py:778
msgid "TAKE CONTROL"
msgstr "السيطرة"
#: selfdrive/controls/lib/alerts.py:197 selfdrive/controls/lib/alerts.py:352
#: selfdrive/controls/lib/alerts.py:359 selfdrive/controls/lib/alerts.py:366
#: selfdrive/controls/lib/alerts.py:373 selfdrive/controls/lib/alerts.py:380
#: selfdrive/controls/lib/alerts.py:387 selfdrive/controls/lib/alerts.py:394
#: selfdrive/controls/lib/alerts.py:401 selfdrive/controls/lib/alerts.py:408
#: selfdrive/controls/lib/alerts.py:415 selfdrive/controls/lib/alerts.py:422
#: selfdrive/controls/lib/alerts.py:429 selfdrive/controls/lib/alerts.py:437
#: selfdrive/controls/lib/alerts.py:445 selfdrive/controls/lib/alerts.py:452
#: selfdrive/controls/lib/alerts.py:459 selfdrive/controls/lib/alerts.py:466
#: selfdrive/controls/lib/alerts.py:473 selfdrive/controls/lib/alerts.py:480
#: selfdrive/controls/lib/alerts.py:487 selfdrive/controls/lib/alerts.py:494
#: selfdrive/controls/lib/alerts.py:501
msgid "TAKE CONTROL IMMEDIATELY"
msgstr "خذ السيطرة على الفور"
#: selfdrive/controls/lib/alerts.py:141
msgid "TOUCH STEERING WHEEL"
msgstr "لمس عجلة القيادة"
#: selfdrive/controls/lib/alerts.py:134
msgid "TOUCH STEERING WHEEL: No Face Detected"
msgstr "لمس عجلة القيادة: لا كشف الوجه"
#: selfdrive/controls/lib/alerts.py:93
msgid "Turn Exceeds Steering Limit"
msgstr "بدوره يتجاوز الحد التوجيهي"
#: selfdrive/controls/lib/alerts.py:721
msgid "Unsupported Giraffe Configuration"
msgstr "تكوين الزرافة غير مدعوم"
#: selfdrive/controls/lib/alerts.py:121
msgid "User Appears Distracted"
msgstr "يظهر المستخدم مشتتا"
#: selfdrive/controls/lib/alerts.py:142
msgid "User Is Unresponsive"
msgstr "المستخدم لا يستجيب"
#: selfdrive/controls/lib/alerts.py:128
msgid "User Was Distracted"
msgstr "المستخدم كان مشتتا"
#: selfdrive/controls/lib/alerts.py:149
msgid "User Was Unresponsive"
msgstr "كان المستخدم لا يستجيب"
#: selfdrive/controls/lib/alerts.py:770
msgid "Vehicle Parameter Identification Failed"
msgstr "فشل تحديد معلمة السيارة"
#: selfdrive/controls/lib/alerts.py:260 selfdrive/controls/lib/alerts.py:595
msgid "Vision Model Output Uncertain"
msgstr "رؤية نموذج الإخراج غير مؤكد"
#: selfdrive/controls/lib/alerts.py:722
msgid "Visit comma.ai/tg"
msgstr "زيارة فاصلة"
#: selfdrive/controls/lib/alerts.py:509 selfdrive/controls/lib/alerts.py:516
msgid "openpilot Canceled"
msgstr "openpilot ملغاة"
#: selfdrive/controls/lib/alerts.py:204 selfdrive/controls/lib/alerts.py:267
#: selfdrive/controls/lib/alerts.py:274 selfdrive/controls/lib/alerts.py:281
#: selfdrive/controls/lib/alerts.py:288 selfdrive/controls/lib/alerts.py:295
#: selfdrive/controls/lib/alerts.py:302 selfdrive/controls/lib/alerts.py:309
#: selfdrive/controls/lib/alerts.py:316 selfdrive/controls/lib/alerts.py:323
#: selfdrive/controls/lib/alerts.py:330 selfdrive/controls/lib/alerts.py:337
#: selfdrive/controls/lib/alerts.py:344 selfdrive/controls/lib/alerts.py:524
#: selfdrive/controls/lib/alerts.py:531 selfdrive/controls/lib/alerts.py:538
#: selfdrive/controls/lib/alerts.py:545 selfdrive/controls/lib/alerts.py:552
#: selfdrive/controls/lib/alerts.py:559 selfdrive/controls/lib/alerts.py:566
#: selfdrive/controls/lib/alerts.py:573 selfdrive/controls/lib/alerts.py:580
#: selfdrive/controls/lib/alerts.py:587 selfdrive/controls/lib/alerts.py:594
#: selfdrive/controls/lib/alerts.py:601 selfdrive/controls/lib/alerts.py:608
#: selfdrive/controls/lib/alerts.py:615 selfdrive/controls/lib/alerts.py:622
#: selfdrive/controls/lib/alerts.py:629 selfdrive/controls/lib/alerts.py:636
#: selfdrive/controls/lib/alerts.py:643 selfdrive/controls/lib/alerts.py:650
#: selfdrive/controls/lib/alerts.py:657 selfdrive/controls/lib/alerts.py:664
#: selfdrive/controls/lib/alerts.py:671 selfdrive/controls/lib/alerts.py:678
#: selfdrive/controls/lib/alerts.py:685
msgid "openpilot Unavailable"
msgstr "openpilot غير متوفر"
